### ISSUE TITLE
Issue(?) With install on Evoq

### ISSUE THREAD

**Issue by moorecreative** [IowaComputerGurus/dnn.scheduledjobs#11]
Is this module not able to run within Evoq, or is there an issue with the DNN version identification at install which might not recognize Evoq versions?

Attempting to install either the new 8.x version or the 7.4 version, both fail the first step of install file upload.

**Comment by mitchelsellers** [comment]
No issues that I am aware of.  Can you share the error message?

**Comment by moorecreative** [comment]
_An unknown error has occured. Please check your installation zip file and try again.
Common issues with bad installation files:
Zip file size is too large, check your IIS settings for max upload file size.
Missing resources in the zip file.
Invalid files in the package.
File extension is not .zip.
Check that you are logged in._

There's nothing specific written to the Event Log, though I could check deeper if needed.

![image](https://user-images.githubusercontent.com/5497943/80545536-9d3c9080-8981-11ea-8323-d357871c08ce.png)

![image](https://user-images.githubusercontent.com/5497943/80545542-a168ae00-8981-11ea-8ead-5ef0ae042b17.png)

![image](https://user-images.githubusercontent.com/5497943/80545574-b80f0500-8981-11ea-8ea0-9586655f0b4a.png)

The older module version installs successfully. To clarify:
- ICG.Modules.ScheduledSqlJobs_07.04.00_Install.zip  This one installs successfully
- ICG.Modules.ScheduledSqlJobs_8.0.4_Install.zip This one gives an error at first install step

**Comment by mitchelsellers** [comment]
Released version 8.0.5 that fixes this

**Comment by moorecreative** [comment]
superb, thanks!
