### ISSUE TITLE
Shrink Database Error: Execution Timeout Expired. 

### ISSUE THREAD

**Issue by JordzJoestar** [IowaComputerGurus/dnn.scheduledjobs#14]
Hi All,

I ran the clean admin logs and that worked great, thank you!

Although I went to shrink database and received this error below, this is on DNN9.1.1 (fragile instance that needs upgrading...).
Error: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

Any suggestions to why this might be happening? Will try on other instances of DNN like 9.2.2 and higher

**Comment by david-poindexter** [comment]
@Gilderroot you may want to make sure your database is in `Simple` recovery model instead of `Full`.  There are arguments these days though that say "best practice" is to not shrink the database.  The big benefit to this tool is the automated clean up of the admin logs!

**Comment by mitchelsellers** [comment]
Anything that runs through SQL Server in DNN Platform is hit with a 30 second timeout limitation.  If your database is large and/or needs to have a lot of space cleanup done, it might not be possible to execute within the context of DNN.

You might need to connect with SQL Server Management Studio to so this for the first time.
