### ISSUE TITLE
This look great but how to install?

### ISSUE THREAD

**Issue by comtsamsmith** [IowaComputerGurus/dnn.scheduledjobs#15]
This DNN module looks like just what I'm looking for since my Eventlog table just brought my site down.

But how to install it into DNN.  No mention on Github, readme or in the manual?

I see the source code. Tried Zipping up the "ScheduleJobs" folder and uploading into DNN.  But reported no resource file contained in ZIp etc.  I'm sure it's easy if you know or are DNN export...  But we are not all experts at everything... :-(

**Comment by david-poindexter** [comment]
@comtsamsmith you can go to [Releases](https://github.com/IowaComputerGurus/dnn.scheduledjobs/releases) and download the install package ZIP.  From there, you can log in to DNN as a super user and visit Settings > Extensions in the PersonaBar (administrative left sidebar).  Click the "Install Extension" button in top right corner.  From there, you simply upload the install package and follow the wizard for installation.  Once installed you can place the module on a page and configure as desired.

Forgive me if there are any typos - I am doing this from my phone and flying a bit blind not having a DNN instance open in front of me to reference.  😉

**Comment by mitchelsellers** [comment]
David's notes are correct.  If you have any issues let us know!

**Comment by mitchelsellers** [comment]
We do have an admin guide available here: https://cdn.iowacomputergurus.com/cdn/Downloads/UserGuides/ICG-SQL-Scheduled-Jobs-AdminGuide.pdf

That might help as well

**Comment by comtsamsmith** [comment]
Ahhh thanks... Going blind in my old age
