### ISSUE TITLE
Support for DNN 8.x and 9.x

### ISSUE THREAD

**Issue by david-poindexter** [IowaComputerGurus/dnn.scheduledjobs#5]
Does v7.4.0 support DNN 8.x and 9.x?

**Comment by mitchelsellers** [comment]
@nvisionative Sorry for the delayed response.  It does, in a way.  We are going to have an 8.x release of this module in the next few days that will have better support for 8.x & 9.x.  

Do you have any feature requirements for this?

**Comment by david-poindexter** [comment]
@mitchelsellers that’s good to hear.  The main thing is having support for the new event log table split introduced in 7.4-ish?

**Comment by david-poindexter** [comment]
Oh, and making sure the module will run okay on DNN 8 & 9!  :)
