### ISSUE TITLE
Extended runtime

### ISSUE THREAD

**Issue by jncraig** [IowaComputerGurus/dnn.scheduledjobs#7]
I have a stored procedure that runs several minutes.

When I try to run it in the Scheduled Jobs module, I get a timeout error.

It would be nice to be able to schedule longer running SQL tasks.

**Comment by mitchelsellers** [comment]
@jncraig Sadly this is a limitation internal to DNN and to support Object Qualifier and DatabaseOwner we have to continue to follow the rules & timeouts set internally to DNN.

If there is a future demand for a non-supported ObjectQualifier/DatabseOwner query we can look at bypassing the DNN Logic to execute.
